library(rafalib)
library(colorspace)
library(RColorBrewer)
mypar(1,1)
display.brewer.all()
cols<-brewer.pal(6, "Dark2")
#setwd("~/Desktop/John/pioneer")
setwd("/mnt/data1/John/pioneer")
LTHSC.me1 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_LTHSC_H3K4me1.bed", header=FALSE))
LTHSC.me2 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_LTHSC_H3K4me2.bed", header=FALSE))
LTHSC.ac <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_LTHSC_H3K27Ac.bed", header=FALSE))
STHSC.me1 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_STHSC_H3K4me1.bed", header=FALSE))
STHSC.me2 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_STHSC_H3K4me2.bed", header=FALSE))
STHSC.ac <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_STHSC_H3K27Ac.bed", header=FALSE))
MPP.me1 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_MPP_H3K4me1.bed", header=FALSE))
MPP.me2 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_MPP_H3K4me2.bed", header=FALSE))
MPP.ac <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_MPP_H3K27Ac.bed", header=FALSE))
CLP.me1 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CLP_H3K4me1.bed", header=FALSE))
CLP.me2 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CLP_H3K4me2.bed", header=FALSE))
CLP.ac <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CLP_H3K27Ac.bed", header=FALSE))
CD4.me1 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CD4_H3K4me1.bed", header=FALSE))
CD4.me2 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CD4_H3K4me2.bed", header=FALSE))
CD4.ac <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CD4_H3K27Ac.bed", header=FALSE))
CD8.me1 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CD8_H3K4me1.bed", header=FALSE))
CD8.me2 <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CD8_H3K4me2.bed", header=FALSE))
CD8.ac <- nrow(read.delim("analysis/chip_seq/tcf1/intersect/intersect_TCF1_CD8_H3K27Ac.bed", header=FALSE))

nLTHSC.me1 <- nrow(read.delim("analysis/chip_seq/macs/LTHSC_H3K4me1_macs_14_peaks.bed"))
nLTHSC.me2 <- nrow(read.delim("analysis/chip_seq/macs/LTHSC_H3K4me2_macs_14_peaks.bed"))
nLTHSC.ac <- nrow(read.delim("analysis/chip_seq/macs/LTHSC_H3K27Ac_macs_14_peaks.bed"))

nSTHSC.me1 <- nrow(read.delim("analysis/chip_seq/macs/STHSC_H3K4me1_macs_14_peaks.bed"))
nSTHSC.me2 <- nrow(read.delim("analysis/chip_seq/macs/STHSC_H3K4me2_macs_14_peaks.bed"))
nSTHSC.ac <- nrow(read.delim("analysis/chip_seq/macs/STHSC_H3K27Ac_macs_14_peaks.bed"))

nMPP.me1 <- nrow(read.delim("analysis/chip_seq/macs/MPP_H3K4me1_macs_14_peaks.bed"))
nMPP.me2 <- nrow(read.delim("analysis/chip_seq/macs/MPP_H3K4me2_macs_14_peaks.bed"))
nMPP.ac <- nrow(read.delim("analysis/chip_seq/macs/MPP_H3K27Ac_macs_14_peaks.bed"))

nCLP.me1 <- nrow(read.delim("analysis/chip_seq/macs/CLP_H3K4me1_macs_14_peaks.bed"))
nCLP.me2 <- nrow(read.delim("analysis/chip_seq/macs/CLP_H3K4me2_macs_14_peaks.bed"))
nCLP.ac <- nrow(read.delim("analysis/chip_seq/macs/CLP_H3K27Ac_macs_14_peaks.bed"))

nCD4.me1 <- nrow(read.delim("analysis/chip_seq/macs/CD4_H3K4me1_macs_14_peaks.bed"))
nCD4.me2 <- nrow(read.delim("analysis/chip_seq/macs/CD4_H3K4me2_macs_14_peaks.bed"))
nCD4.ac <- nrow(read.delim("analysis/chip_seq/macs/CD4_H3K27Ac_macs_14_peaks.bed"))

nCD8.me1 <- nrow(read.delim("analysis/chip_seq/macs/CD8_H3K4me1_macs_14_peaks.bed"))
nCD8.me2 <- nrow(read.delim("analysis/chip_seq/macs/CD8_H3K4me2_macs_14_peaks.bed"))
nCD8.ac <- nrow(read.delim("analysis/chip_seq/macs/CD8_H3K27Ac_macs_14_peaks.bed"))

MPP.me1/nMPP.me1

me1 <- c(LTHSC.me1/nLTHSC.me1, STHSC.me1/nSTHSC.me1, MPP.me1/nMPP.me1, CLP.me1/nCLP.me1, CD4.me1/nCD4.me1, CD8.me1/nCD8.me1)
me2 <- c(LTHSC.me2/nLTHSC.me2, STHSC.me2/nSTHSC.me2, MPP.me2/nMPP.me2, CLP.me2/nCLP.me2, CD4.me2/nCD4.me2, CD8.me2/nCD8.me2)
ac <- c(LTHSC.ac/nLTHSC.ac, STHSC.ac/nSTHSC.ac, MPP.ac/nMPP.ac, CLP.ac/nCLP.ac, CD4.ac/nCD4.ac, CD8.ac/nCD8.ac)
#mypar(1,1)
#png("/mnt/data1/John/pioneer/analysis/chip_seq/plot/Intersect_TCF1_MARKS.png")
#mypar(1,3)
barplot(me1, ylim=c(0,1), cex.names=1.5, names.arg=c("LT-HSC","ST-HSC","MPP","CLP","CD4","CD8"),col=cols,ylab = "Proportion", main="Overlap of TCF1 and H3K4me1")
barplot(me2, ylim=c(0,1), cex.names=1.5,names.arg=c("LT-HSC","ST-HSC","MPP","CLP","CD4","CD8"),col=cols,ylab = "Proportion", main="Overlap of TCF1 and H3K4me2")
barplot(ac, ylim=c(0,1), cex.names=1.5,names.arg=c("LT-HSC","ST-HSC","MPP","CLP","CD4","CD8"),col=cols,ylab = "Proportion", main="Overlap of TCF1 and H3K27Ac")
#dev.off()